services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - ./frontend/dist:/var/www/html/public/vue
    working_dir: /var/www/html
    networks:
      - balanso-network
    depends_on:
      - db
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1

  db:
    image: mysql:8
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: balanso
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - balanso-network

  frontend:
    image: node:18
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app
      - ./frontend/node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173" # Проброс порта для Vue
    networks:
      - balanso-network

volumes:
  db_data:

networks:
  balanso-network:
    driver: bridge
